spring:
  application:
    name: eureka-server

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
server:
  port: 8761

eureka:
   client:
      service-url:
        defaultZone=http://localhost:8761/eureka/:



datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 4795895q
  driver-class-name: org.postgresql.Driver
